[package]
name = "duckarmor/freeze"
authors = ["duckarmor"]
description = "Immutable data structures for Roblox Luau ❄️"
version = "0.1.2"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
exclude = ["bin", "docs", ".moonwave", "build", "tests", "*spec.lua", "*d.luau"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"
